<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <EnableDefaultScopedCssItems>false</EnableDefaultScopedCssItems>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RunAOTCompilation>true</RunAOTCompilation>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RouteTrace.Core\RouteTrace.Core.csproj" />
  </ItemGroup>

  <Target Name="BuildFrontend" BeforeTargets="ResolveScopedCssInputs">
    <Exec Command="npm run build" />
    <ItemGroup>
      <_GeneratedScopedCss Include=".generated\scopedcss-input\**\*.razor.css" />
      <ScopedCssInput Include="@(_GeneratedScopedCss)">
        <RazorComponent>%(RecursiveDir)%(Filename)</RazorComponent>
      </ScopedCssInput>
    </ItemGroup>
  </Target>

</Project>
